
### GET /courses

GET http://localhost:3000/courses HTTP/1.1


### POST[ok] /users

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name": "Admin",
  "email": "admin@email.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

### POST[Bad Request] /users

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name": "",
  "email": "adminemail.com",
  "password": "1234",
  "passwordConfirmation": "1234"
}
